/* 
 * Handshake
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PostApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class PostApiTests
    {
        private PostApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PostApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PostApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' PostApi
            //Assert.IsInstanceOfType(typeof(PostApi), instance, "instance is a PostApi");
        }

        /// <summary>
        /// Test PostGetclosepostsGet
        /// </summary>
        [Test]
        public void PostGetclosepostsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.PostGetclosepostsGet();
            
        }
        /// <summary>
        /// Test PostPost
        /// </summary>
        [Test]
        public void PostPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //InsertPostData body = null;
            //instance.PostPost(body);
            
        }
    }

}
